# Generated by Django 5.2 on 2025-05-04 14:32

import datetime
import django.db.models.deletion
import multiselectfield.db.fields
import tuition_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone', models.CharField(max_length=10)),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone', models.CharField(max_length=10)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('dob', models.DateField(default=datetime.date.today)),
                ('img', models.ImageField(blank=True, default='student_img/fallback.png', upload_to='student_img/')),
                ('standard', models.CharField(choices=[('8', '8th'), ('9', '9th'), ('10', '10th'), ('12', '12th')], max_length=2)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('SSC', 'SSC'), ('HSC', 'HSC')], max_length=4)),
                ('school', models.CharField(blank=True, choices=[('Saint Michael School', 'Saint Michael School'), ('Orchid School', 'Orchid School'), ('Sai Angel School', 'Sai Angel School'), ('Icon Public School', 'Icon Public School'), ('Takshila School', 'Takshila School'), ('Podar School', 'Podar School'), ('Auxilium Convent School', 'Auxilium Convent School'), ('Sacred Heart Convent School', 'Sacred Heart Convent School'), ('Ashokbhau Firodia School', 'Ashokbhau Firodia School'), ('Athare Patil School', 'Athare Patil School'), ('NA', 'Not Applicable')], max_length=50, null=True)),
                ('hsc_school', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(choices=[('Gulmohar', 'Gulmohar'), ('Market Yard', 'Market Yard')], max_length=20)),
                ('subject', multiselectfield.db.fields.MultiSelectField(choices=[('English (Tuition + Test Series)', 'English (Tuition + Test Series)'), ('Social Studies (Tuition + Test Series)', 'Social Studies (Tuition + Test Series)'), ('Grammar (Tuition + Test Series)', 'Grammar (Tuition + Test Series)'), ('English (Test Series)', 'English (Test Series)'), ('Social Studies (Test Series)', 'Social Studies (Test Series)')], max_length=1000)),
                ('fees', models.CharField(max_length=2000)),
                ('installment_plan', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('amount1', models.IntegerField()),
                ('amount2', models.IntegerField(blank=True, default=None, null=True)),
                ('payment_mode1', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], max_length=10)),
                ('payment_mode2', models.CharField(blank=True, choices=[('online', 'Online'), ('cash', 'Cash')], default=None, max_length=10, null=True)),
                ('payment_proof1', models.FileField(blank=True, null=True, upload_to=tuition_app.models.StudentRegistration.unique_filename)),
                ('payment_proof2', models.FileField(blank=True, default=None, null=True, upload_to=tuition_app.models.StudentRegistration.unique_filename)),
                ('full_fee_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition_app.studentregistration')),
            ],
        ),
    ]
