# Generated by Django 5.2 on 2025-05-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='hsc_school',
            new_name='school_text',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='fee_structure',
            field=models.TextField(default='fees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='school',
            field=models.CharField(blank=True, choices=[('Saint Michael School', 'Saint Michael School'), ('Orchid School', 'Orchid School'), ('Sai Angel School', 'Sai Angel School'), ('Icon Public School', 'Icon Public School'), ('Takshila School', 'Takshila School'), ('Podar School', 'Podar School'), ('Auxilium Convent School', 'Auxilium Convent School'), ('Sacred Heart Convent School', 'Sacred Heart Convent School'), ('Ashokbhau Firodia School', 'Ashokbhau Firodia School'), ('Athare Patil School', 'Athare Patil School'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
