# Generated by Django 5.2 on 2025-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0002_rename_hsc_school_studentregistration_school_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='school_text',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
