# Generated by Django 5.2 on 2025-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0003_alter_studentregistration_school_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='full_fee_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
