# Generated by Django 5.2 on 2025-05-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0004_alter_studentregistration_full_fee_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='amount2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
