# Generated by Django 5.2 on 2025-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_app', '0005_alter_studentregistration_amount2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='amount1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
